// Bubblewrap CLI configuration for the RSVP Reader PWA.
//
// Bubblewrap reads this file (or a similar one generated by `init`) to build
// the Android project, generate keystore fingerprints, and produce a
// signed, upload-ready APK / AAB.
//
// Typical usage:
//   npx @bubblewrap/cli init --manifest=https://zipang.id/rsvp/manifest.json
//   # bubblewrap writes twa-manifest.json next to this file
//   # edit the packageId and signingKey below, then:
//   npx @bubblewrap/cli build
//
// See ./README.md for the full build/sign/upload workflow.

module.exports = {
  // The Android application id (Play Store "package name").
  packageId: 'id.zipang.rsvp',

  // Where the PWA is hosted. Bubblewrap uses this to fetch the manifest and
  // to set up the Trusted Web Activity verifier.
  host: 'zipang.id',
  webManifestUrl: 'https://zipang.id/rsvp/manifest.json',

  // Display / theme — matches the PWA's dark+red palette.
  name: 'RSVP Reader',
  launcherName: 'RSVP',
  display: 'standalone',
  orientation: 'portrait',
  statusBarColor: '#1a1a1a',
  navigationColor: '#1a1a1a',
  backgroundColor: '#1a1a1a',
  themeColor: '#1a1a1a',

  // Splash + monochrome icons (large icon used on the Android splash).
  iconUrl: 'https://zipang.id/rsvp/icons/icon-512.png',
  splashScreenUrl: 'https://zipang.id/rsvp/icons/icon-512.png',
  monochromeIconUrl: 'https://zipang.id/rsvp/icons/icon-192.png',

  // App version — bump versionCode for every Play Console upload.
  appVersion: '1.1.0',
  appVersionCode: 110,

  // Optional features. Disabled by default to keep the APK minimal.
  enableNotifications: false,
  features: {
    appsFlyer: false,
    playBilling: false,
  },

  // Signing config. Run the keytool command in README.md to create
  // android.keystore, then drop its SHA-256 fingerprint into
  // twa-manifest.json and assetlinks.json before uploading.
  signingKey: {
    path: './android.keystore',
    alias: 'android',
  },

  // Fall back to Chrome Custom Tabs if the TWA verifier cannot be satisfied
  // (e.g. user is on a non-Chrome browser). Keeps the app installable on
  // every device.
  fallbackType: 'customtabs',
};
